### ISSUE TITLE
selenium Attribute Error while trying to download

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/AparatDownloader#4]
when we click on download button on `GUI`; we get an **error** in the terminal that says `AttributeError: 'WebDriver' object has no attribute 'find_elements_by_css_selector'`. the whole error log is below:
```
DevTools listening on ws://127.0.0.1:2621/devtools/browser/4a3d03fb-d71e-4bf1-93e9-67f63797b891
[6084:5316:0803/110134.485:ERROR:device_event_log_impl.cc(214)] [11:01:34.485] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\edris\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\edris\Desktop\Projects\AparatDownloader\AparatDownloader.py", line 80, in download
    downloader.downloadFromPlayList(txtUrl.get())
  File "C:\Users\edris\Desktop\Projects\AparatDownloader\AparatDownloader.py", line 54, in downloadFromPlayList
    links = browser.find_elements_by_css_selector(
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_css_selector'
[6084:11296:0803/110232.263:ERROR:util.cc(127)] Can't create base directory: C:\Program Files\Google\GoogleUpdater
Traceback (most recent call last):
  File "C:\Users\edris\Desktop\Projects\AparatDownloader\AparatDownloader.py", line 94, in <module>
    root.mainloop()
  File "C:\Users\edris\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
```

## What the hack is wrong Here? 🙄
Actually selenium `3.0` uses selectors in a different way that it used to be 3 years a go. so we need to ship to code to the new version.

## How to fix the issue?
as Docs says we should import `from selenium.webdriver.common.by import By` and use `browser.find_element(By.XPATH,selector)`

**Comment by edrisranjbar** [comment]
- [x] change play list selector: `a.titled-link.title[data-refer=playlists]`
- [x] change download Popup selector: `#primary > div.single-details > div.single-details__info > div.single-details__utils > div > div > div.download-button > div > div > button`
- [x] 720 Download Button: `//*[@id="720p"]/div/span/span`
- [x] 10s wait after page loads (for both **playlist** and **single video** downloading)
